<h3>Help</h3>
<ol>
    <li><b>Starting an IQdesktop container</b>
        <ul>
            <li>Select your required settings (version of IQdesktop, number of cores, needed memory)
            <li>You can also select a 'dark' and a 'light' theme
            <li>To start a container you might have received a 'Start Password' - enter it. This is to avoid that someone else can start (or stop) a container under your username
            <li>Click 'START'
        </ul>
    <li><b>Connecting to a container</b>
        <ul>
            <li><a href='https://iqdesktop.intiquan.com/book/vnc.html' target='new'>Get and execute TigerVNC Viewer (explained here)</a>
            <li>Enter: iqdesktop.intiquan.com:THE_NUMBER_IN_THE_VNC_Port column for your container
            <li>Click 'Connect'
            <li>Enter the password that was provided to you - for demo purposes same as the Start Password
            <li>Click 'OK'
            <li>Note: for the purpose of this demo server the VNC connection is not encrypted. You can still <a href='https://iqdesktop.intiquan.com/book/secureconnection.html#ssh-tunneling' target='new'>ensure an encrypted connection through SSH tunneling</a>
        </ul>
    <li><b>Stopping an IQdesktop container</b>
        <ul>
            <li>Enter your 'Start Password' - if you have received one
            <li>Click 'STOP'
        </ul>
</ol>
