<table class="shaded">
<tr>
<td class="top" width="40%">
<h3>Test running IQdesktop</h3>
<ol>
    <li><b>Starting IQdesktop</b>
        <ul>
            <li>Select your required settings (version of IQdesktop, number of cores, needed memory)
            <li>You can also select a 'dark' and a 'light' theme
            <li>Enter the 'Start Password' (on the demo system it is the same as the indicated 'Username')
            <li>Click 'START'
        </ul>
    <li><b>Connecting to IQdesktop</b>
        <ul>
            <li><a href='https://iqdesktop.intiquan.com/book/vnc.html' target='new'>Get and execute TigerVNC Viewer (explained here)</a>
            <li>Enter: <span style="color:#f4A033; font-weight:bold; font-family:monospace;">iqdesktop.intiquan.com:THE_NUMBER_IN_THE_VNC_Port</span> column below
            <li>Click 'Connect'
            <li>Enter the password that was provided to you. Or on the Demo system:
                <ul>
                    <li>PUBLIC version: 'password'
                    <li>Controlled version: Same as the 'Start Password'
                </ul>
            <li>Click 'OK'
        </ul>
    <li><b>Stopping IQdesktop</b>
        <ul>
            <li>Enter your 'Start Password' 
            <li>Click 'STOP'
        </ul>
</ol>
</td>
<td class="top">
<h3>Disclaimer</h3>
<b>Access to the demo server</b><br>
IntiQuan provides access to the IQdesktop demo server as a convenience and on a best effort basis without any warranties. 
Multiple demo instances for different people may be running in parallel on the same demo server. 
For demo purposes no encryption of communication with the server is set up. 
If you want to run NONMEM, MONOLIX, or MATLAB then you will need to bring your own licenses. We can explain how to 
set them up in IQdesktop - it is easy and no one else will have access to these.
<p>
<b>Data integrity and security</b><br>
IntiQuan does not accept any responsibility or liability with regards to the availability of the system nor to the integrity 
and security of any data stored on the remote IQdesktop demo system. For this reason, please consider carefully if or which data you 
upload to the IQdesktop demo server.
<p>
<b>No backup</b><br>
Please consider that data from the demo server is not backed up by IntiQuan. It is the sole responsibility of the user to ensure
the backup of their data. The demo IQdesktop system is set up to stop automatically after a certain time (see below). IntiQuan 
reserves the right to stop any running IQdesktop systems at any point in time without prior warning.
When your instance is stopped, including but not limited to a reboot of the server, a software failure, expiration of the maximum run time,
or by the InitQuan administrator, all the data stored within the instance will be 
lost without any possibility to retrieve it again. IntiQuan will not be liable in any way for such losses. 
<p>
<b>Web Server Log files</b><br>
Log files are generated that record the IP address from which the web server is accessed, the date and the clicks that were made.
Only essential information are collected. By using this demo service you agree to the collection of these log data. Your activities
inside an IQdesktop system are not monitored or logged.
</div>
</td>
</tr>
</table>
<div style="font-size:10px;">