<table class="shaded">
<tr>
<td class="top">
<h3>Help</h3>
<ol>
    <li><b>Starting an IQdesktop container</b>
        <ul>
            <li>Select your required settings (version of IQdesktop, number of cores, needed memory)
            <li>You can also select a 'dark' and a 'light' theme
            <li>To start a container you might have received a 'Start Password' - enter it. This is to avoid that someone else can start (or stop) a container under your username
            <li>Click 'START'
        </ul>
    <li><b>Connecting to a container</b>
        <ul>
            <li><a href='https://iqdesktop.intiquan.com/book/vnc.html' target='new'>Get and execute TigerVNC Viewer (explained here)</a>
            <li>Enter: iqdesktop.intiquan.com:THE_NUMBER_IN_THE_VNC_Port column for your container
            <li>Click 'Connect'
            <li>Enter the password that was provided to you - for demo purposes same as the Start Password
            <li>Click 'OK'
            <li>Note: for the purpose of this demo server the VNC connection encryption is disabled. 
        </ul>
    <li><b>Stopping an IQdesktop container</b>
        <ul>
            <li>Enter your 'Start Password' - if you have received one
            <li>Click 'STOP'
        </ul>
</ol>
</td>
<td class="top">
<h3>Disclaimer</h3>
<b>Access to the server</b><br>
We provide access to the IQdesktop demo server as a convenience and on a best effort basis without any warranties. 
Multiple demo instances for different people may be running in parallel on the same demo server. 
For demo purposes no encryption of communication with the server is set by default. If you would like an encrypted connection, 
contact us in advance. If you want to run NONMEM, MONOLIX, or MATLAB then you will need to bring your own license keys. 
We can explain how to set them up in IQdesktop.
<p>
<b>Data integrity and security</b><br>
IntiQuan does not accept any responsibility or liability with regards to the availability of the system nor to the integrity 
and security of any data stored on the remote IQdesktop demo system. For this reason, please consider carefully which data you 
upload to the IQdesktop demo server.
<p>
<b>No backup</b><br>
Please consider that data from the demo server is not backed up by IntiQuan. It is the sole responsibility of the user to ensure
the backup of their data. The test instance usually keeps running as long as the server is up. IntiQuan reserves the right to 
stop instances, for any reason including excessive use or long-term idling. When your instance is stopped, either due to a 
reboot of the server, a software failure, or by the InitQuan administrator, all the data stored within the instance will be 
lost without any possibility to retrieve it again. IntiQuan will not be liable in any way for such losses. 
<p>
<b>Web Server Log files</b><br>
Log files are generated that record the IP address from which the web server is accessed, the date and the clicks that were made.
Only essential information are collected. By using this demo service you agree to the collection of these log data. Your activities
inside an IQdesktop system are not monitored or logged.
</div>
</td>
</tr>
</table>
<div style="font-size:10px;">