<?php
// Define displayed column names in table
$NAME_TH_TEXT = "Name";
$USER_TH_TEXT = "Username";
$SAFETY_CHECK_TH_TEXT = "Start Password";
$PASSWORD_TH_TEXT = "Password";
$IMAGE_TH_TEXT = "IQdesktop Version";
$VOLUME_MAP_TH_TEXT = "Mapped Drive";
$VNCPORT_TH_TEXT = "VNC Port";
$SSHPORT_TH_TEXT = "SSH Port";
$SHINY_SERVER_PORT_TH_TEXT = "Shiny Server Port";
$ALLOW_SUDO_TH_TEXT = "Sudo Rights";
$SSH_SERVER_TH_TEXT = "SSH Server";
$ALLOW_SHINY_SERVER_TH_TEXT = "Shiny Server";
$USER_ID_TH_TEXT = "User ID";
$THEME_TH_TEXT = "Theme";
$MAC_TH_TEXT = "MAC Address";
$SHM_SIZE_GB_TH_TEXT = "Shared Mem Size";
$NR_CORES_TH_TEXT = "Nr Cores";
$MEMORY_GB_TH_TEXT = "Memory [GB]";
$TIMEZONE_TH_TEXT = "Timezone";
$IQRTOOLS_COMPLIANCE_TH_TEXT = "IQR Tools Compliance";
$IQREPORT_TEMPLATE_TH_TEXT = "IQReport Template";
?>