<?php
// User page - Get passed GET variables
$do = $_GET["do"];
$csvfile = $_GET["csvfile"];

// User page - Get passed POST variables
$control = $_POST["control"];
$user = $_POST["user"];
$action = $_POST["action"];
$image = $_POST["image"];
$nrcores = $_POST["nrcores"];
$memgb = $_POST["memgb"];
$theme = $_POST["theme"];
$safety_check = $_POST["safety_check"];
$safety_check_required = $_POST["safety_check_required"];
?>